In [1]:
import plotly.offline
from plotly.graph_objs import Scatter, Layout
import numpy as np
import pandas as pd

In [16]:

a = np.array([1, 2, 3])
b = np.ones((3, 3))
c = np.array([5, 10, 20])

In [7]:
print(a)
print(a.shape)
print(b)
print(b.shape)
print(c)
print(c.shape)


[1 2 3]
(3,)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
(3, 3)


In [15]:
print(a*b)

[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]


In [9]:
print(np.dot(a, b))

[ 6.  6.  6.]


In [13]:
print(np.outer(a, b))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]]


In [17]:
print(a*c)

[ 5 20 60]


In [22]:
print(a * c.T)

[ 5 20 60]


In [34]:
print(np.dot(a, b))

[[ 6.  6.  6.]]


In [35]:
print(np.dot(a.T, b))

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [37]:

a = np.array([[1, 2, 3]])
b = np.ones((3, 3))
c = np.array([[5, 10, 20]])
print(a)
print(a.shape)
print(b)
print(b.shape)
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
(3, 3)
[[ 5 10 20]]
(1, 3)


In [24]:
print(a*c)

[[ 5 20 60]]


In [25]:
print(a * c.T)

[[ 5 10 15]
 [10 20 30]
 [20 40 60]]


In [26]:
print(a.T * c.T)

[[ 5]
 [20]
 [60]]


In [27]:
print(a.T * c)

[[ 5 10 20]
 [10 20 40]
 [15 30 60]]


In [31]:
print(np.dot(a, b))

[[ 6.  6.  6.]]


In [32]:
print(np.dot(a, c.T))

[[85]]


In [33]:
print(np.dot(a.T, c))

[[ 5 10 20]
 [10 20 40]
 [15 30 60]]
